<?php 

    $current_series= [
        'ACTION COMICS', 'AMERICAN VAMPIRE 1976', 'AQUAMAN', 'BATGIRL', 'BATMAN', 'BATMAN BEYOND', 'BATMAN/SUPERMAN', 'BATMAN/SUPERMAN ANNUAL', 'BATMAN: THE JOKER WAR ZONE',
        'BATMAN: THREE JOKERS',  ["title" => "BATMAN: WHITE KNIGHT", "IMMAGINARY_HOST" => "PRESENTS: HARLEY QUINN"], 'CATWOMAN'
        ]

?>